sudo: true
dist: bionic
os: linux
language: bash
services:
  - docker
before_install:
  - sed -i 's/#INSERT_HERE/COPY . \/mod_event_kafka/g' .devcontainer/Dockerfile
  - cat .devcontainer/Dockerfile
  - docker build -t mod_event_kafka -f .devcontainer/Dockerfile .
  - docker run mod_event_kafka make -C /mod_event_kafka
script:
  -  docker run -i mod_event_kafka bash -c "cd /mod_event_kafka && make && ls"
